name: Docker Image CI

on:
  push:
    branches: [ master | aarch64 ]
  pull_request:
    branches: [ master | aarch64]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
